add ability to theme song text independently
johanfrick/custom-sonos-card pull request #55
Opened 2022-03-19 07:59 UTC by finity69x2

As asked for in the release thread. I figured I'd just do it to help you out.

Hopefully it is OK.

2022-03-19 09:59 UTC, johanfrick requested changes

2022-03-19 09:59 UTC, johanfrick commented on src/main.ts
> +          --sonos-int-song-text-color: var(--sonos-song-text-color, var(--accent-color));
This should default back to Sonos accent Color.
Also please update readme 🙂

2022-03-19 10:00 UTC, johanfrick commented
Thanks for helping out! Just some minor tweaks needed 🙂

2022-03-19 12:47 UTC, johanfrick approved these changes
👍👍🍾

2022-03-19 12:48 UTC, merged

2022-03-19 12:49 UTC, finity69x2 commented
I hope that is what you meant. I'm not sure how variables are inherited.

updated readme as well.

2022-03-19 16:28 UTC, johanfrick commented
Really nice @finity69x2 !
I’ll make a release tomorrow 🙂

2022-03-20 17:31 UTC, johanfrick commented
https://github.com/johanfrick/custom-sonos-card/releases/tag/v4.1.0